In [1]:
print("setup working")

setup working

In [2]:
import pandas as pd
import numpy as np

print("Libraries loaded")

Libraries loaded

In [3]:
import os

print("Project path:", os.getcwd())
print("Ready for data ingestion")

Project path: D:\bluestock_mf_capstone\notebooks
Ready for data ingestion

In [4]:
print("hello")

hello

In [5]:
print("data ingestion start")

data ingestion start

In [6]:
import pandas as pd

In [7]:
import os
print(os.listdir("../data/raw"))

[]

In [8]:
import os
print(os.listdir("../data/raw"))

['01_fund_master.csv', '02_nav_history.csv', '03_aum_by_fund_house.csv', '04_monthly_sip_inflows.csv', '05_category_inflows.csv', '06_industry_folio_count.csv', '07_scheme_performance.csv', '08_investor_transactions.csv', '09_portfolio_holdings.csv', '10_benchmark_indices.csv']

In [9]:
df = pd.read_csv("../data/raw/01_fund_master.csv")
df.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     str
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: float64(2), int64(3), str(10)
memory usage: 4.8 KB

In [11]:
df["launch_date"] = pd.to_datetime(df["launch_date"])
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   amfi_code           40 non-null     int64
 1   fund_house          40 non-null     str
 2   scheme_name         40 non-null     str
 3   category            40 non-null     str
 4   sub_category        40 non-null     str
 5   plan                40 non-null     str
 6   launch_date         40 non-null     datetime64[us]
 7   benchmark           40 non-null     str
 8   expense_ratio_pct   40 non-null     float64
 9   exit_load_pct       40 non-null     float64
 10  min_sip_amount      40 non-null     int64
 11  min_lumpsum_amount  40 non-null     int64
 12  fund_manager        40 non-null     str
 13  risk_category       40 non-null     str
 14  sebi_category_code  40 non-null     str
dtypes: datetime64[us](1), float64(2), int64(3), str(9)
memory usage: 4.8 KB

In [12]:
import datetime

df["fund_age_years"] = (pd.Timestamp("today") - df["launch_date"]).dt.days / 365
df.head()

,amfi_code,fund_house,scheme_name,category,sub_category,plan,launch_date,benchmark,expense_ratio_pct,exit_load_pct,min_sip_amount,min_lumpsum_amount,fund_manager,risk_category,sebi_category_code,fund_age_years
0,119551,SBI Mutual Fund,SBI Bluechip Fund - Regular Plan - Growth,Equity,Large Cap,Regular,2006-02-14,NIFTY 100 TRI,1.54,1.0,500,1000,Sohini Andani,Moderate,EC01,20.317808
1,119552,SBI Mutual Fund,SBI Bluechip Fund - Direct Plan - Growth,Equity,Large Cap,Direct,2013-01-01,NIFTY 100 TRI,0.66,1.0,500,1000,Sohini Andani,Moderate,EC01,13.432877
2,119598,SBI Mutual Fund,SBI Small Cap Fund - Regular Plan - Growth,Equity,Small Cap,Regular,2009-09-09,BSE 250 SmallCap TRI,1.43,1.0,500,1000,R. Srinivasan,Very High,EC03,16.747945
3,119599,SBI Mutual Fund,SBI Small Cap Fund - Direct Plan - Growth,Equity,Small Cap,Direct,2013-01-01,BSE 250 SmallCap TRI,0.72,1.0,500,1000,R. Srinivasan,Very High,EC03,13.432877
4,119120,SBI Mutual Fund,SBI Magnum Gilt Fund - Regular Plan - Growth,Debt,Gilt,Regular,2000-12-30,CRISIL Dynamic Gilt Index,0.77,0.0,500,1000,Dinesh Ahuja,Low,DC02,25.446575

In [13]:
import pandas as pd
import os

files = os.listdir("../data/raw")
files

['01_fund_master.csv',
 '02_nav_history.csv',
 '03_aum_by_fund_house.csv',
 '04_monthly_sip_inflows.csv',
 '05_category_inflows.csv',
 '06_industry_folio_count.csv',
 '07_scheme_performance.csv',
 '08_investor_transactions.csv',
 '09_portfolio_holdings.csv',
 '10_benchmark_indices.csv']

In [14]:
import pandas as pd
import os

data_path = "../data/raw"

files = os.listdir(data_path)

dfs = {}

for file in files:
    dfs[file] = pd.read_csv(os.path.join(data_path, file))

dfs.keys()

dict_keys(['01_fund_master.csv', '02_nav_history.csv', '03_aum_by_fund_house.csv', '04_monthly_sip_inflows.csv', '05_category_inflows.csv', '06_industry_folio_count.csv', '07_scheme_performance.csv', '08_investor_transactions.csv', '09_portfolio_holdings.csv', '10_benchmark_indices.csv'])

In [15]:
for name, df in dfs.items():
    print("\n", name)
    print(df.shape)
    print(df.columns)

 01_fund_master.csv
(40, 15)
Index(['amfi_code', 'fund_house', 'scheme_name', 'category', 'sub_category',
       'plan', 'launch_date', 'benchmark', 'expense_ratio_pct',
       'exit_load_pct', 'min_sip_amount', 'min_lumpsum_amount', 'fund_manager',
       'risk_category', 'sebi_category_code'],
      dtype='str')

 02_nav_history.csv
(46000, 3)
Index(['amfi_code', 'date', 'nav'], dtype='str')

 03_aum_by_fund_house.csv
(90, 5)
Index(['date', 'fund_house', 'aum_lakh_crore', 'aum_crore', 'num_schemes'], dtype='str')

 04_monthly_sip_inflows.csv
(48, 6)
Index(['month', 'sip_inflow_crore', 'active_sip_accounts_crore',
       'new_sip_accounts_lakh', 'sip_aum_lakh_crore', 'yoy_growth_pct'],
      dtype='str')

 05_category_inflows.csv
(144, 3)
Index(['month', 'category', 'net_inflow_crore'], dtype='str')

 06_industry_folio_count.csv
(21, 6)
Index(['month', 'total_folios_crore', 'equity_folios_crore',
       'debt_folios_crore', 'hybrid_folios_crore', 'others_folios_crore'],
      dtype='str')

 07_scheme_performance.csv
(40, 19)
Index(['amfi_code', 'scheme_name', 'fund_house', 'category', 'plan',
       'return_1yr_pct', 'return_3yr_pct', 'return_5yr_pct',
       'benchmark_3yr_pct', 'alpha', 'beta', 'sharpe_ratio', 'sortino_ratio',
       'std_dev_ann_pct', 'max_drawdown_pct', 'aum_crore', 'expense_ratio_pct',
       'morningstar_rating', 'risk_grade'],
      dtype='str')

 08_investor_transactions.csv
(32778, 13)
Index(['investor_id', 'transaction_date', 'amfi_code', 'transaction_type',
       'amount_inr', 'state', 'city', 'city_tier', 'age_group', 'gender',
       'annual_income_lakh', 'payment_mode', 'kyc_status'],
      dtype='str')

 09_portfolio_holdings.csv
(322, 8)
Index(['amfi_code', 'stock_symbol', 'stock_name', 'sector', 'weight_pct',
       'market_value_cr', 'current_price_inr', 'portfolio_date'],
      dtype='str')

 10_benchmark_indices.csv
(8050, 3)
Index(['date', 'index_name', 'close_value'], dtype='str')

In [16]:
print("KEY RELATIONSHIP CHECK")

print("\nFund Master unique keys:", dfs["01_fund_master.csv"]["amfi_code"].nunique())
print("NAV records:", len(dfs["02_nav_history.csv"]))

print("\nScheme Performance keys:", dfs["07_scheme_performance.csv"]["amfi_code"].nunique())
print("Portfolio holdings:", len(dfs["09_portfolio_holdings.csv"]))

KEY RELATIONSHIP CHECK

Fund Master unique keys: 40
NAV records: 46000

Scheme Performance keys: 40
Portfolio holdings: 322

In [17]:
fund_master = dfs["01_fund_master.csv"]

nav = dfs["02_nav_history.csv"]

print("Join check:")
print("NAV matching AMFI codes:", nav["amfi_code"].isin(fund_master["amfi_code"]).sum())
print("Total NAV rows:", len(nav))

Join check:
NAV matching AMFI codes: 46000
Total NAV rows: 46000

In [18]:
print("""
DATABASE DESIGN (Mutual Fund Analytics)

1. FUND MASTER (Dimension Table)
   - amfi_code (PK)
   - fund_house
   - scheme_name
   - category
   - risk_category

2. NAV HISTORY (Fact Table)
   - amfi_code (FK)
   - date
   - nav

3. SCHEME PERFORMANCE (Fact Table)
   - amfi_code (FK)
   - returns, alpha, beta

4. PORTFOLIO HOLDINGS (Fact Table)
   - amfi_code (FK)
   - stock details
""")

DATABASE DESIGN (Mutual Fund Analytics)

1. FUND MASTER (Dimension Table)
   - amfi_code (PK)
   - fund_house
   - scheme_name
   - category
   - risk_category

2. NAV HISTORY (Fact Table)
   - amfi_code (FK)
   - date
   - nav

3. SCHEME PERFORMANCE (Fact Table)
   - amfi_code (FK)
   - returns, alpha, beta

4. PORTFOLIO HOLDINGS (Fact Table)
   - amfi_code (FK)
   - stock details